---
title: "QC for objects"
output: html_notebook
---


```{r}
rm(list=ls()) 
suppressPackageStartupMessages({
  library(monocle3)
  library(reticulate)
  library(openxlsx)  
  library(dplyr)
  library(Matrix)
  library(ggplot2)
  library(xfun)
  # library(pals)
  library(rhdf5)
  library(RColorBrewer)
  library(Signac)
  library(Seurat)
  library(future)
  library(GenomicRanges)
  library(ComplexHeatmap)
  library(EnsDb.Hsapiens.v86)
  library(BSgenome.Hsapiens.UCSC.hg38)
  #library(JASPAR2020)
  library(TFBSTools)
  library(ArchR)
  library(parallel)
  library(scCustomize)
  library(pbmcapply)
  library(msigdbr)
  library(SeuratObject)
  library(tibble)
  library(ggrepel)
  library(Rcpp)
})

set.seed(1234)

dyn.load('/app/software/ArrayFire/3.8.1/lib64/libaf.so.3')

library(RcppArrayFire)
library(viewmaster)
```

#load objects
```{r}

setwd("/fh/fast/furlan_s/user/owalt/ewings/multiome/all_parents")
m1<- loadArchRProject("/fh/fast/furlan_s/user/owalt/ewings/multiome/all_parents")
m1_seu<-readRDS("all_parents_seurat.rds")
remove(m1_seu)


setwd("/fh/fast/furlan_s/user/owalt/ewings/multiome/knockdown")
m3<-loadArchRProject()
m3_seu<-readRDS("knockdown_seurat.rds")

```

# m1 qc stats
```{r}
all_parents_cols<-c("A4573"="#D51F26","A673"="#272E6A","CHLA9"="#208A42","CHLA10"="#89288F","PDX305"="#F47D2B", "RDES"="#FEE500","SKNMC"="#8A9FD1","TC32"="#3BBCA8","TC71"="#E6C2DC",
               "hMSC_parent_240"="#90D5E4",  "hMSC_parent"="#89C75F","hMSC.h7"="#F37B7D","RD_parent"="#78385c","U2OS_parent"="#C06CAB")


pdf("/fh/fast/furlan_s/user/owalt/ewings/multiome/qc/m1_qc.pdf", width = 16, height = 4)
VlnPlot(m1_seu, features = c("Gex_nGenes", "Gex_nUMI", "TSSEnrichment", "ReadsInBlacklist", "nFrags"), group.by = "cell_line", cols = all_parents_cols, pt.size= 0, ncol = 5)
dev.off()

```

# m3 qc stats
```{r}
kd_cols<-c("A673_shNS"="#272E6A","A673_shFLI1"="#5362e6","CHLA10_shNS"="#89288F", "CHLA10_shFLI1" = "#ea42f5", "PDX305_shNS"="#F47D2B", "PDX305_shFLI1" = "#fcc59f", "TC71_shNS"="#c49bb8", "TC71_shFLI1"= "#fac5eb")

pdf("/fh/fast/furlan_s/user/owalt/ewings/multiome/qc/m3_qc.pdf", width = 15, height = 4)
VlnPlot(m3_seu, features = c("Gex_nGenes", "Gex_nUMI", "TSSEnrichment", "ReadsInBlacklist", "nFrags"), group.by = "cell_line", cols = kd_cols, pt.size= 0, ncol = 5)
dev.off()

```

# patient scRNA qc stats
```{r}
kd_cols<-c("A673_shNS"="#272E6A","A673_shFLI1"="#5362e6","CHLA10_shNS"="#89288F", "CHLA10_shFLI1" = "#ea42f5", "PDX305_shNS"="#F47D2B", "PDX305_shFLI1" = "#fcc59f", "TC71_shNS"="#c49bb8", "TC71_shFLI1"= "#fac5eb")

pdf("/fh/fast/furlan_s/user/owalt/ewings/multiome/qc/m3_qc.pdf", width = 15, height = 4)
VlnPlot(m3_seu, features = c("Gex_nGenes", "Gex_nUMI", "TSSEnrichment", "ReadsInBlacklist", "nFrags"), group.by = "cell_line", cols = kd_cols, pt.size= 0, ncol = 5)
dev.off()

```