---
title: "CellSignal"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
rm(list=ls())
#BiocManager::install("zellkonverter")
ROOT_DIR<-"/fh/fast/furlan_s/user/owalt/ewings"
stem<-"bulk_RNA_patient"
DATA_DIR <- file.path(ROOT_DIR,  stem,  "data")      # SPECIFY HERE
RES_DIR  <- file.path(ROOT_DIR,  stem, "res")     # SPECIFY HERE
RMD_DIR  <- file.path(ROOT_DIR,  stem, "rmd")     # SPECIFY HERE
CDS_DIR <- file.path(ROOT_DIR,  stem, "rds")
FIG_DIR <- file.path(ROOT_DIR,  stem, "figs")

suppressPackageStartupMessages({
  library(monocle3)
  library(m3addon)
  library(reticulate)
  library(openxlsx)  
  library(dplyr)
  library(Matrix)
  library(ggplot2)
  library(xfun)
  library(pals)
  #library(zellkonverter)
  library(RColorBrewer)
  library(Signac)
  library(Seurat)
  library(ggplot2)
  library(openxlsx)
  library(future)
  library(EnsDb.Hsapiens.v86)
  library(SummarizedExperiment)
  library(ComplexHeatmap)
  library(patchwork)
  library(stringr)
  library(ggsignif)
  library(ggpubr)
  library(data.table)
  library(DESeq2)
  library(oligo)
  library(huex10sttranscriptcluster.db)
  library(affycoretools)
  library(pd.huex.1.0.st.v2)
  library(survival)
  library(lubridate)
  library(ggsurvfit)
  library(gtsummary)
  library(tidycmprsk)
  library(condsurv)
})

library(reticulate)
py_config()
```

```{r helpful functions}

meta<-euro_meta
fix_meta<-function(meta){
  
  idx_to_fix<-which(grepl("charac", names(meta)))
  #i<-idx_to_fix[7]
  for(i in idx_to_fix){
      print(i)
      name<-meta[,i] %>% str_split(": ",) %>% sapply("[[", 1) %>% unique()
      name<-name[name != ""]
      name<-gsub(" ", "_", name)
      name<-gsub("\\(", "", name)
      name<-gsub(")", "", name)
      names(meta)[i]<-name
      data<-meta[,i] %>% str_split(": ",) 
      meta[,i]<-sapply(data, function(x){
        if(length(x) >1){
          x[2]
        }else{
          x
        }
      })
  }
  
  return(meta)
}

```

# patient microarray dataset
```{r set up file paths}
# -------------------------------------

# -------------------------------------
# find relative directory on Server
# -------------------------------------
#https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE63157

series_meta<-read.csv("/fh/fast/furlan_s/user/owalt/ewings/EwingMA/GSE63157_meta.csv") %>% t() %>% as.data.frame()
colnames(series_meta)<-series_meta[1,]
series_meta<-series_meta[-1,]
colnames(series_meta)<-gsub("!", "", colnames(series_meta))
colnames(series_meta)<-gsub("Sample_", "", colnames(series_meta))
series_meta %>% head()
dim(series_meta)
rownames(series_meta)<-series_meta$geo_accession

names(series_meta)[10]<-"study"
# fix COG meta
cog_meta<-series_meta[series_meta$study %in% c("study: AEWS0031","study: INT-0154"),]

#Euro meta

euro_meta<-series_meta[!series_meta$study %in% c("study: AEWS0031","study: INT-0154"),] 
colnames(euro_meta)<-make.unique(names(euro_meta))
euro_meta<-euro_meta[,!names(euro_meta)%in%c("characteristics_ch1.7","characteristics_ch1.8","characteristics_ch1.9") ]

euro_meta<-fix_meta(euro_meta)
cog_meta<-fix_meta(cog_meta)

names(euro_meta)[names(euro_meta) == "efs_0=no_event,_1=event"]<-"efs_event"
names(euro_meta)[names(euro_meta) == "os_0=alive;_1=dead"]<-"survival_status"
names(euro_meta)[names(euro_meta) == "efs-time"]<-"efs_time_days"
names(euro_meta)[names(euro_meta) == "os-time"]<-"survival_time_days"

names(euro_meta)[!names(euro_meta) %in% names(cog_meta)]

merged <- full_join(cog_meta, euro_meta)
rownames(merged)<-merged$geo_accession

names(merged)

merged$efs_event_0_1<-merged$efs_event
merged$efs_event_0_1[merged$efs_event_0_1 %in% c("No event", "0")]<-0
merged$efs_event_0_1[merged$efs_event_0_1 %in% c("Relapse", "SMN", "1")]<-1
merged$efs_event_0_1<-as.numeric(merged$efs_event_0_1)

merged$efs_time_days <- as.numeric(merged$efs_time_days)
merged$survival_time_days <- as.numeric(merged$survival_time_days)

merged$survival_status_0_1<-merged$survival_status
merged$survival_status_0_1[merged$survival_status_0_1 %in% c("Dead", "1")]<-1
merged$survival_status_0_1[merged$survival_status_0_1 %in% c("Alive", "0")]<-0
merged$survival_status_0_1<-as.numeric(merged$survival_status_0_1)

merged<-merged[,!names(merged) == "efs_time"]

key<-"/fh/fast/furlan_s/user/owalt/ewings"
flag<-"tumorinvasion_MA"
setwd(file.path(key, flag))
# -------------------------------------
# specify paths and load functions
# -------------------------------------
DATA_DIR <- file.path( key,flag,  "CEL") # SPECIFY HERE
RES_DIR  <- file.path(  key,flag, "res")      # SPECIFY HERE


series_mtx<-read.csv("/fh/fast/furlan_s/user/owalt/ewings/EwingMA/GSE63157_series_matrix.csv")

head(series_mtx)
rownames(series_mtx)<-series_mtx$ID_REF
series_mtx<-series_mtx[,-1]

obj<-CreateSeuratObject(counts = series_mtx, meta.data = merged)
obj[["normRNA"]]<-CreateAssayObject(counts = series_mtx)

bulk_count_data<-obj@assays$normRNA@counts
```

# map probe ids to gene_short_names and ensembl ids
```{r build microarray object}
setwd("/fh/fast/furlan_s/user/owalt/ewings/tumorinvasion_MA/GSE63157_RAW")
CELfiles<-list.files()
rawData <- read.celfiles(CELfiles[CELfiles != "core"])
getClass("GeneFeatureSet")

exprs(rawData)[1:4,1:3]
filename <- sampleNames(rawData)

#filter features by genes
geneset<-oligo::rma(rawData, target = "core")
# BiocManager::install(geneset@annotation)

geneAcc=as.character(huex10sttranscriptclusterACCNUM[rownames(geneset)])
geneNames=as.character(huex10sttranscriptclusterSYMBOL[rownames(geneset)])

geneset<-annotateEset(geneset,huex10sttranscriptcluster.db) #remove probes that don't have a gene

Biobase::exprs(geneset) %>% head()

mat<-Biobase::exprs(geneset)
colnames(mat)<-colnames(mat) %>% strsplit("_")%>% sapply("[[", 2)%>% strsplit("\\.")%>% sapply("[[", 1)

fdat<- geneset@featureData@data
names(fdat)<-c("id", "entrez", "gene_short_name", "description")

write.csv(fdat, "/fh/fast/furlan_s/user/owalt/ewings/EwingMA/probe_gene_short_name_mappings.csv")

library(org.Hs.eg.db)

ensembl_ids <- mapIds(org.Hs.eg.db,
  keys = fdat$gene_short_name,
  column = "ENSEMBL",
  keytype = "SYMBOL",
  multiVals = "first"
)

ensembl_ids[names(ensembl_ids) %in% fdat$gene_short_name] %>% length()
fdat$gene_short_name %>% length()
gene_short_name = fdat$gene_short_name[fdat$gene_short_name %in% names(ensembl_ids)]
ensembl_ids<-ensembl_ids[order(match(names(ensembl_ids), fdat$gene_short_name))] 
ensembl_ids<-ensembl_ids %>% unlist()

ensembl_ids %>% length()
gene_short_name <- gene_short_name[gene_short_name %in% names(ensembl_ids)]
gene_short_name %>% length()

gene_mapping <- data.frame(
  gene_short_name = gene_short_name,
  ensembl_gene_id = ensembl_ids
)

gtf <- rtracklayer::import('/fh/fast/furlan_s/user/owalt/ewings/bulk_RNA_patient/data/gencode.v33.annotation.gtf')
gtf_df <- as.data.frame(gtf)

bulk_count_data<-bulk_count_data[rownames(bulk_count_data) %in% fdat$id,]
fdat_sub<-fdat[fdat$id %in% rownames(bulk_count_data),]

dim(bulk_count_data)
dim(fdat_sub)
fdat_sub[fdat_sub$id == rownames(bulk_count_data)[37],]


rownames(bulk_count_data)<-fdat_sub$gene_short_name[order(match(fdat_sub$id, rownames(bulk_count_data)))]
bulk_count_data_filt<-bulk_count_data[!is.na(rownames(bulk_count_data)),]
dim(bulk_count_data_filt)

gene_mapping<-gene_mapping[gene_mapping$gene_short_name %in% rownames(bulk_count_data_filt),]
gene_mapping<-gene_mapping[order(match(gene_mapping$gene_short_name, rownames(bulk_count_data_filt))),]

rownames(bulk_count_data_filt)<-gene_mapping$ensembl_gene_id
gene_mapping[gene_mapping$ensembl_gene_id == rownames(bulk_count_data_filt)[1],]


gtf_df$gene_id<-str_split(gtf_df$gene_id, "\\.") %>% sapply("[[",1)
gtf_df$gene_id %in% rownames(bulk_count_data_filt) %>% table()
merge<-cbind(bulk_count_data_filt, gtf_df[match(rownames(bulk_count_data_filt), gtf_df$gene_id),])

merge$size<-merge$end - merge$start
bulk_count_data_filt<-cbind(data.frame(size = merge$size), bulk_count_data_filt)

dim(bulk_count_data_filt)

cn<-colnames(bulk_count_data_filt)
rownames(bulk_count_data_filt)<-make.unique(rownames(bulk_count_data_filt)%>% strsplit("\\.")  %>% sapply("[[", 1))


write.csv(bulk_count_data_filt,"/fh/fast/furlan_s/user/owalt/ewings/EwingMA/bulk_count_data.csv",  row.names = rownames(bulk_count_data_filt))


bulk_meta_data = obj@meta.data
write.csv(bulk_meta_data,"/fh/fast/furlan_s/user/owalt/ewings/EwingMA/bulk_meta_data.csv")



# se<-SummarizedExperiment(assays = list(counts = mat), colData = meta, rowData = fdat )
# 
DefaultAssay(obj)<-"normRNA"
saveRDS(obj, "/fh/fast/furlan_s/user/owalt/ewings/EwingMA/microarray_seurat_20260112.rds")
```

