
```{r, warning=FALSE, message=FALSE, warning=FALSE, echo=F}

quit("no")
graphics.off()
rm(list=ls())
.libPaths(c("~/R/x86_64-pc-linux-gnu-library/4.2", .libPaths()))
# 
# BW_DIR<-"/fh/fast/furlan_s/user/owalt/ewings/hoxd13/GSE182512_RAW"

#Load neccessary packages
suppressPackageStartupMessages({
  library(monocle3)
  library(reticulate)
  library(clusterProfiler)
  library(enrichplot)
  library(openxlsx)  
  library(dplyr)
  library(Matrix)
  library(ggplot2)
  library(xfun)
  # library(pals)
  library(rhdf5)
  library(pals)
  library(Signac)
  library(Seurat)
  library(future)
  library(ggrepel)
  library(GenomicRanges)
  library(RColorBrewer)
  library(ComplexHeatmap)
  # library(EnsDb.Hsapiens.v86)
  # library(BSgenome.Hsapiens.UCSC.hg38)
  library(JASPAR2020)
  library(TFBSTools)
  library(ArchR)
  library(parallel)
  library(scCustomize)
  library(org.Hs.eg.db)
  library(SeuratObject)
  library(msigdbr)
  library(stringr)
  library(tibble)
  library(FigR)
  library(pbmcapply)
  library(fgsea)
  library(viridis)
})
# does not work with h5
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.3", repos = BiocManager::repositories())

#trying to find on that works with h5 files
devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories())


Sys.setenv(MODULEPATH="/app/modules/all", MODULEPATH_ROOT="/app/modules/all", MODULESHOME="/app/lmod/lmod")
source("/app/lmod/lmod/init/R", echo=FALSE, max=Inf)
module("load", "MACS2/2.2.6-foss-2019b-Python-3.7.4")

#make cairo functional
knitr::opts_chunk$set(dev="CairoPNG")

detach("package:ArchR", unload=TRUE)
library(ArchR)

#load objects and set seed
set.seed(1234)
setwd("~/m2") 

#set up parallelization and increase memory for R environment
library(future)
plan()

plan("multisession", workers = detectCores())
options(future.globals.maxSize = 36000000 * 1024 ^ 3) # for 50 Gb RAM

#version 11 cuda
dyn.load('/app/software/ArrayFire/3.8.1/lib64/libaf.so.3')

library(RcppArrayFire)
library(viewmaster)
```

```{r colors }
cell_line_cols<-c( "A673" = "#272E6A", "CHLA9"= "#208A42", "CHLA10" = "#89288F", "TC32" = "#00bca8", "PDX305"= "#F47D2B", "SKNMC"= "#8A9FD1", "A4573" = "#D51F26", "TC71" = "#e9c2db","RDES" = "#FEE500")
subgroup_cols<-c("group.1"= "#9d8cbf","group.2" = "#12733c","group.3"= "#edd30c")

cluster_cols<-c( "C1" = "#2d3aad",
                 "C2" = "#01031f",
                 "C3" = "#D51F26",
                 "C4" = "#d64b50",
                 "C5" = "#78181b",
                 "C6" = "#8ed1f5",
                 "C7" = "#739cff",
                 "C8" = "#5e5cab",
                 "C9" = "#abbeed",
                 "C10" = "#8A9FD1",
                 "C11" = "#e9c2db",
                 "C12" = "#d17bb2",
                 "C13" = "#FEE500",
                 "C14" = "#bfb341",
                 "C15" = "#ded8a4",
                 "C16" = "#00bca8",
                 "C17" = "#10665d",
                 "C18" = "#77a39f",
                 "C19" = "#8a3c07",
                 "C20" = "#eb9d67",
                 "C21" = "#F47D2B",
                 "C22" = "#89288F",
                 "C23" = "#b452ba",
                 "C24" = "#208a42",
                 "C25" = "#06541f")

rna_cols<-paletteContinuous(n=8)[c(1:3, 6:8)]

pal<- rev(mako(n=9))
pal<-pal[1:8]
pal<-c("#ffffff", pal)
mtf_cols<-pal
```

#MAKE M2
```{r subset master project}
#i had to subset the master object for this analysis, ignore this step if it's not necessary

ew4<-loadArchRProject(path = "~/EW4")

m2<-subsetArchRProject(
  ArchRProj = ew4,
  cells = getCellNames(ew4[ew4$cell_line %in% c("A4573", "A673", "SKNMC", "TC32", "PDX305", "CHLA10", "CHLA9", "TC71", "RDES"),]),
  outputDirectory = "~/m2",
  dropCells = TRUE,
  logFile = NULL,
  threads = getArchRThreads(),
  force = T
)

m2@projectMetadata$outputDirectory<-"~/m2"

saveArchRProject(m2, outputDirectory = "~/m2", overwrite = T)
```

```{r reduce dimensions}
#normal workflow for creating and analyzing archr objects, 
m2<- loadArchRProject()

setwd("~/m2")

getAvailableMatrices(m2)

m2 <- addIterativeLSI(
    ArchRProj = m2,
    useMatrix = "TileMatrix", 
    name = "ATAC_LSI", 
    iterations = 5, 
    varFeatures = 10000, 
    dimsToUse = 1:15,
    force=T,
    LSIMethod = 1
)

m2 <- addUMAP(
    ArchRProj = m2,
    reducedDims = "ATAC_LSI",
    name = "ATAC_UMAP",
    nNeighbors = 20,
    minDist = 0.5,
    metric = "cosine",
    force=T
)


p<-plotEmbedding(ArchRProj = m2, colorBy = "cellColData", name = "cell_line", embedding = "ATAC_UMAP", palette =  "stallion2")
plotPDF(p, name = "ATAC_UMAP.pdf", ArchRProj = m2, addDOC = FALSE, width = 8, height = 10)

m2 <- addIterativeLSI(
    ArchRProj = m2, 
    clusterParams = list(
      resolution = 0.2, 
      cell_lineCells = 10000,
      n.start = 10
    ),
    saveIterations = FALSE,
    useMatrix = "GeneExpressionMatrix", 
    depthCol = "Gex_nUMI",
    varFeatures = 2500,
    firstSelection = "variable",
    binarize = FALSE,
    name = "LSI_RNA"
)


m2 <- addUMAP(
    ArchRProj = m2,
    reducedDims = "LSI_RNA",
    name = "RNA_UMAP",
    nNeighbors = 30,
    minDist = 0.5,
    metric = "cosine"
)

p<-plotEmbedding(m2, name = "cell_line", embedding = "RNA_UMAP", size = 1.5, labelAsFactors=F, labelMeans=F)
plotPDF(p, name = "RNA_UMAP.pdf", ArchRProj = m2, addDOC = FALSE, width = 8, height = 10)

#combined RNA and ATAC DIMS to create multiome embedding
m2 <- addCombinedDims(m2, reducedDims = c("LSI_RNA", "ATAC_LSI"), name =  "mo")

m2 <- addUMAP(
    ArchRProj = m2,
    reducedDims = "mo",
    name = "mo_UMAP",
    nNeighbors = 30,
    minDist = 0.5,
    metric = "cosine"
)

m2 <- addImputeWeights(m2, reducedDims = "mo")

p<-plotEmbedding(m2, name = "cell_line", embedding = "mo_UMAP", size = 0.5, labelAsFactors=T, labelMeans=F)

plotPDF(p, name = "mo_UMAP.pdf", ArchRProj = m2, addDOC = FALSE, width = 8, height = 10)+scale_color_manual(values = c("A673" = "#D51F26", "CHLA9"= "#208A42", "CHLA10" = "#89288F", "TC32" = "#00bca8", "PDX305"= "#F47D2B", "SKNMC"= "#8A9FD1", "A4573" = "#272E6A", "TC71" = "#e9c2db","RDES" = "#FEE500"))
```

```{r call peaks}
#Call peaks on ArchR object
m2 <- addGroupCoverages(ArchRProj = m2, groupBy = "cell_line", force = T)

#if you're running on rhino make sure to ml MACS2 before launching R, if you're running locally you need to install macs2 with python..definitely less messy to run on rhino
pathToMacs2 <- findMacs2()

m2 <- addReproduciblePeakSet(
    ArchRProj = m2, 
    groupBy = "cell_line", 
    pathToMacs2 = pathToMacs2
)

m2 <- addPeakMatrix(m2)

getAvailableMatrices(m2)

m2 <- addPeak2GeneLinks(
    ArchRProj = m2,
    reducedDims = "mo",
    useMatrix = "GeneExpressionMatrix"
)

saveArchRProject(m2, outputDirectory = "~/m2", overwrite = T)
```

```{r ChomVAR moitf annotations}
mtfs<-chromVARmotifs::human_pwms_v2
names(mtfs) <- names(mtfs) %>% strsplit("_") %>% sapply("[[", 3)

m2 <- addMotifAnnotations(ArchRProj = m2, name = "Motif", force = T, motifPWMs = mtfs)
m2 <- addBgdPeaks(m2, force = T)

m2 <- addDeviationsMatrix(
  ArchRProj = m2, 
  peakAnnotation = "Motif",
  force = TRUE, threads=1
)

saveArchRProject(m2)
```

```{r JASPAR moitf annotations}
m2 <- addMotifAnnotations(ArchRProj = m2, annoName = "JASPAR_Motif", force = T, motifSet = "JASPAR2020", species = "Homo sapiens")
m2 <- addBgdPeaks(m2, force = T)
#sometimes this is just better to run in terminal....
m2 <- addDeviationsMatrix(
  ArchRProj = m2, 
  peakAnnotation = "JASPAR_Motif",
  force = TRUE,
  threads = 1
)

saveArchRProject(m2)
getAvailableMatrices(m2)

Sys.setenv(HDF5_USE_FILE_LOCKING=FALSE,RHDF5_USE_FILE_LOCKING=FALSE)
```

#Make ewing clusters
```{r}
setwd("~/m2")

m2 <- addClusters(
    input = m2,
    reducedDims = "mo",
    method = "Seurat",
    name = "Clusters",
    resolution = 1.75,
    force=T
)
```

#MAKE Seurat
```{r}
m2<-loadArchRProject()

t<-viewmaster::archR_to_seurat(m2, matrix = "GeneExpressionMatrix", binarize = F, archr_rd = "mo_UMAP")
seu<-NormalizeData(t) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()

mtf<-getMatrixFromProject(m2, "MotifMatrix", binarize = F)
mat<-mtf@assays@data$z
# colnames(mat)<-gsub("#", "_", colnames(mat))
seu[["MotifMatrix"]]<-CreateAssayObject(mat)
DefaultAssay(seu)<-"MotifMatrix"

peak<-getMatrixFromProject(m2, "PeakMatrix", binarize = F)
mat<-peak@assays@data$PeakMatrix
feature_df <- peak@rowRanges %>% as.data.frame()
rn <- paste0(feature_df[, 1], "-", feature_df[, 2], "-", 
            feature_df[, 3])
rownames(mat)<-rn
# colnames(mat)<-gsub("#", "_", colnames(mat))
seu[["ATAC"]]<-CreateAssayObject(mat)

gene_score<-getMatrixFromProject(m2, "GeneScoreMatrix", binarize = F)
mat<-gene_score@assays@data$GeneScoreMatrix
rownames(mat)<-gene_score@elementMetadata$name

# colnames(mat)<-gsub("#", "_", colnames(mat))
seu[["GeneScoreMatrix"]]<-CreateAssayObject(mat)
m2_seu<-seu

DimPlot(m2_seu, group.by = "cell_line")
saveRDS(m2_seu, "~/m2/m2.rds")
```

