


```{r, echo=FALSE, warning=F, message=F}
rm(list=ls())
knitr::opts_chunk$set(fig.width=10, fig.height=5,
                      echo=FALSE, warning=FALSE, message=FALSE)
knitr::opts_chunk$set(dev.args=list(bg="transparent"))
graphics.off()
ROOT_DIR<-"/fh/fast/furlan_s/user/owalt/ewings"
stem<-"bulk_RNA_patient"
DATA_DIR <- file.path(ROOT_DIR,  stem,  "data")      # SPECIFY HERE
RES_DIR  <- file.path(ROOT_DIR,  stem, "res")     # SPECIFY HERE
RMD_DIR  <- file.path(ROOT_DIR,  stem, "rmd")     # SPECIFY HERE
CDS_DIR <- file.path(ROOT_DIR,  stem, "rds")
FIG_DIR <- file.path(ROOT_DIR,  stem, "figs")
suppressPackageStartupMessages({
  library(DESeq2)
  library(apeglm)
  library(ggplot2)
  library(ggrepel)
  library(readxl)
  library(pheatmap)
  library(knitr)
  library(tidyverse)
  library(data.table)
  library(tools)
  library(xfun)
  library(RColorBrewer)
  library(openxlsx)
  library(monocle3)
  library(m3addon)
  library(msigdbr)
  library(Seurat)
})
```


# Make object
```{r}
se<-readRDS(file.path(CDS_DIR, "summarizedExperiment.RDS"))
#colData(se)$filenames
colnames(se)<-colData(se)$sample

bch<-fread(file.path(DATA_DIR, "BCH.txt"))
sj<-fread(file.path(DATA_DIR, "SJ.txt"))
sj$'Sample Name'
bch$'Sample Name'
bch$'submitted_subject_id'
sj$'submitted_subject_id'
sj$Group2<-sj$'submitted_subject_id'
bch$Group2<-bch$'submitted_subject_id'
sj$Group<-sj$Group2
bch$Group<-bch$Group2
celllines<-c("Cado-ES1", "A673", "EWS834",  "TC71" ,"SKNEP1", "EW8", "TC32", "RDES","6647", "TTC466", "CHLA9", "CHP100L", "ES6","EW8", "SKES1","SKNLO","SKPNETLi", "TTC466", "TTC475","CHLA258", "EWS502", "EWS834", "CHLA352","ES1","ES2", "ES4" ,"ES7","ES8","RDES","SKNEP1","SKNMC", "TC138" ,"TC244","TC248", "TC253" ,"TC4C", "TTC547", "TC240", "TC106", "TC215")
sj$Group[!sj$Group2 %in% celllines]<-"Primary"
bch$Group[!bch$Group2 %in% celllines]<-"Primary"
sj$body_site<-NA
ctk<-intersect(colnames(bch), colnames(sj))

meta1<-rbind(as.data.frame(bch)[,ctk], as.data.frame(sj)[,ctk])
metaf<-meta1[match(colnames(se), meta1$Run),]
rownames(metaf)<-metaf$Run

metaf$body_site[is.na(metaf$body_site)]<-"Other"
metaf$body_site2<-metaf$body_site
bs2<-c('Cell_Line', 'Other', 'Other', 'Other', 'Other', 'Other', 'Leg', 'Axial_Met', 'Cell_Line', 'Cell_Line', 'Other', 'Axial', 'Pelvic', 'Chest', 'Leg', 'Leg', 'Other', 'Chest_Met', 'Other', 'Lung_Met', 'Cell_Line', 'Axial', 'Cell_Line', 'Lung_Met', 'Leg', 'Axial', 'Cell_Line', 'Other', 'Cell_Line', 'Axial', 'Chest_Met', 'Cell_Line', 'Cell_Line', 'Axial', 'Cell_Line', 'Chest_Met', 'Chest', 'Pelvic', 'Cell_Line', 'Other', 'Leg', 'Other', 'Cell_Line', 'Axial', 'Leg', 'Cell_Line', 'Cell_Line', 'Axial_Met', 'Other', 'Leg', 'Cell_Line', 'Other', 'Other', 'Other', 'Other', 'Leg', 'Chest', 'Shoulder', 'Cell_Line', 'Cell_Line', 'Other', 'Cell_Line', 'Shoulder', 'Other', 'Other', 'Axial', 'Chest', 'Arm_Met', 'Other', 'Leg', 'Other', 'Chest', 'Other', 'Cell_Line', 'Leg', 'Axial', 'Pelvic', 'Chest_Met', 'Axial', 'Chest', 'Leg', 'Pelvic', 'Chest', 'Cell_Line', 'Cell_Line', 'Cell_Line', 'Pelvic', 'Other', 'Other', 'Cell_Line', 'Cell_Line', 'Other', 'Other', 'Lung_Met', 'Other', 'Axial_Met', 'Chest', 'Other', 'Cell_Line', 'Cell_Line', 'Other', 'Axial_Met', 'Cell_Line', 'Other', 'Cell_Line', 'Other', 'Axial', 'Cell_Line', 'Cell_Line', 'Cell_Line', 'Cell_Line', 'Other', 'Chest', 'Other', 'Lung_Met', 'Lung_Met', 'Other', 'Leg', 'Other', 'Leg', 'Other', 'Other', 'Chest', 'Other', 'Abdominal', 'Abdominal')
#table(bs2)
metaf$body_site2<-bs2

col<-c(as.character(pals::polychrome()[c(1,3:36)]), "grey")
names(col)<-c(levels(factor(metaf$Group))[-17], "Primary")

colData(se)<-cbind(colData(se), metaf)

dds<-DESeqDataSet(se, design=~BioProject)
dds1<-dds[,dds$BioProject %in% levels(factor(dds$BioProject))[1]]
dds2<-dds[,dds$BioProject %in% levels(factor(dds$BioProject))[2]]

keep <- rowSums(counts(dds1)) > 0 & rowSums(counts(dds2)) > 0
dds <- dds[keep,]
dds <- estimateSizeFactors(dds)
dds@assays@data$normalized_counts <- counts(dds, normalized=TRUE)
saveRDS(dds, file.path(CDS_DIR, "bulkRNA_dds.rds"))
```

```{r seurat object}
mat<-assays(dds)$normalized_counts
rownames(mat)<-rowData(dds)$gene_short_name
seu<-CreateSeuratObject(counts = mat, meta.data = colData(dds) %>% as.data.frame())
saveRDS(seu, file.path(CDS_DIR, "bulkRNA_seurat.rds"))
```

