---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list=ls())
suppressPackageStartupMessages({
   library(monocle3)
  # library(reticulate)
  library(openxlsx)  
  library(dplyr)
  library(Matrix)
  library(ggplot2)
  library(xfun)
  # library(pals)
  library(rhdf5)
  library(RColorBrewer)
  library(Signac)
  library(Seurat)
  library(ggplot2)
  library(future)
  library(GenomicRanges)
  library(ComplexHeatmap)
  library(EnsDb.Hsapiens.v86)
  library(BSgenome.Hsapiens.UCSC.hg38)
  library(JASPAR2020)
  library(TFBSTools)
  library(ArchR)
  library(parallel)
  library(pbapply)
  library(pbmcapply)
  library(scCustomize)
  library(SeuratObject)
})

Sys.setenv(MODULEPATH="/app/modules/all", MODULEPATH_ROOT="/app/modules/all", MODULESHOME="/app/lmod/lmod")
source("/app/lmod/lmod/init/R", echo=FALSE, max=Inf)
module("load", "MACS2/2.2.6-foss-2019b-Python-3.7.4")

#version 11 cuda
dyn.load('/app/software/ArrayFire/3.8.1/lib64/libaf.so.3')
options(future.globals.maxSize = 360 * 1024 ^ 3) # for 50 Gb RAM
knitr::opts_chunk$set(dev="CairoPNG")

library(RcppArrayFire)
library(viewmaster)
```

#M1 ARCHR
```{r subset from master }
ew4<-loadArchRProject(path = "/fh/fast/furlan_s/user/owalt/ewings/multiome/EW4")

m1<-subsetArchRProject(
  ArchRProj = ew4,
  cells = getCellNames(ew4[ew4$cell_line %in% c("A4573", "A673", "SKNMC", "TC32", "PDX305", "CHLA10", "CHLA9", "TC71", "RDES", "hMSC_parent_240","RD_parent", "hMSC_parent", "U2OS_parent" , "hMSC.h7"),]),
  outputDirectory = "/fh/fast/furlan_s/user/owalt/ewings/multiome/all_parents",
  dropCells = TRUE,
  logFile = NULL,
  threads = getArchRThreads(),
  force = T
)

m1@projectMetadata$outputDirectory<-"/fh/fast/furlan_s/user/owalt/ewings/multiome/all_parents"

saveArchRProject(m1, outputDirectory = "/fh/fast/furlan_s/user/owalt/ewings/multiome/all_parents", overwrite = F)

setwd("/fh/fast/furlan_s/user/owalt/ewings/multiome/all_parents")

m1<- loadArchRProject()

m1@projectMetadata$outputDirectory <- "/fh/fast/furlan_s/user/owalt/ewings/multiome/all_parents"
getOutputDirectory(m1)
```

```{r reduce dimensions }
m1 <- addIterativeLSI(
    ArchRProj = m1,
    useMatrix = "TileMatrix", 
    name = "ATAC_LSI", 
    iterations = 5, 
    varFeatures = 10000, 
    dimsToUse = 1:15,
    force=T,
    LSIMethod = 1
)

getArchRThreads()
m1 <- addUMAP(
    ArchRProj = m1,
    reducedDims = "ATAC_LSI",
    name = "ATAC_UMAP",
    nNeighbors = 20,
    minDist = 0.5,
    metric = "cosine",
    force=T
)


p<-plotEmbedding(ArchRProj = m1, colorBy = "cellColData", name = "cell_line", embedding = "ATAC_UMAP")
plotPDF(p, name = "ATAC_UMAP.pdf", ArchRProj = m1, addDOC = FALSE, width = 8, height = 10)

getAvailableMatrices(m1)

m1 <- addIterativeLSI(
    ArchRProj = m1, 
    clusterParams = list(
      resolution = 0.2, 
      cell_lineCells = 10000,
      n.start = 10
    ),
    saveIterations = FALSE,
    useMatrix = "GeneExpressionMatrix", 
    depthCol = "Gex_nUMI",
    varFeatures = 2500,
    firstSelection = "variable",
    binarize = FALSE,
    name = "LSI_RNA"
)


m1 <- addUMAP(
    ArchRProj = m1,
    reducedDims = "LSI_RNA",
    name = "RNA_UMAP",
    nNeighbors = 30,
    minDist = 0.5,
    metric = "cosine",
    force=T
)

p<-plotEmbedding(m1, name = "cell_line", embedding = "RNA_UMAP", size = 1.5, labelAsFactors=F, labelMeans=F)
plotPDF(p, name = "RNA_UMAP.pdf", ArchRProj = m1, addDOC = FALSE, width = 8, height = 10)

#mo Dims
m1 <- addCombinedDims(m1, reducedDims = c("LSI_RNA", "ATAC_LSI"), name =  "mo")

m1 <- addUMAP(
    ArchRProj = m1,
    reducedDims = "mo",
    name = "mo_UMAP",
    nNeighbors = 50,
    minDist = 0.6,
    metric = "cosine",
    force = T
)

m1 <- addImputeWeights(m1, reducedDims = "mo")
m1 <- addGroupCoverages(ArchRProj = m1, groupBy = "cell_line", force = T)
saveArchRProject(m1)
```

Build rest of object
```{bash}
cd /fh/fast/furlan_s/user/owalt/ewings/multiome/all_parents
module load R/4.2
ml MACS2
sbatch -n 1 -c 30 -p campus-new --mem-per-cpu=21000MB --wrap='Rscript build_ArchR_object.R'
```

#MAKE Seurat
```{r}
m1<-loadArchRProject()
se <- getMatrixFromProject(m1, useMatrix = "GeneExpressionMatrix", binarize = F)
mat <- se@assays@data@listData[["GeneExpressionMatrix"]]
feature_df <- se@elementMetadata %>% as.data.frame()
rn <- feature_df$name
rownames(mat) <- rn
colnames(mat) <- colnames(se)
meta <- se@colData %>% as.data.frame()
rownames(meta) <- colnames(mat)
seu <- CreateSeuratObject(mat %>% as.sparse(), project = "GeneExpressionMatrix", assay = "GeneExpressionMatrix", meta.data = meta)
keyname <- paste0("mo_UMAP", "_")
umap_df <- m1@embeddings@listData[["mo_UMAP"]]@listData[["df"]] %>% as.matrix()
colnames(umap_df) <- paste0(keyname, 1:2)
seu@reductions[["mo_UMAP"]] <- Seurat::CreateDimReducObject(embeddings = umap_df, 
                                                           key = keyname, assay = "GeneExpressionMatrix")
seu

t<-UpdateSeuratObject(seu)
seu<-NormalizeData(seu) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()

mtf<-getMatrixFromProject(m1, "MotifMatrix", binarize = F)
mat<-mtf@assays@data$z
# colnames(mat)<-gsub("#", "_", colnames(mat))
t[["MotifMatrix"]]<-CreateAssayObject(mat %>% as.sparse())
peak<-getMatrixFromProject(m1, "PeakMatrix", binarize = F)
mat<-peak@assays@data$PeakMatrix
feature_df <- peak@rowRanges %>% as.data.frame()
rn <- paste0(feature_df[, 1], "-", feature_df[, 2], "-", 
            feature_df[, 3])
rownames(mat)<-rn
t[["ATAC"]]<-CreateAssayObject(mat %>% as.sparse())

gene_score<-getMatrixFromProject(m1, "GeneScoreMatrix", binarize = F)
mat<-gene_score@assays@data$GeneScoreMatrix
rownames(mat)<-gene_score@elementMetadata$name
t[["GeneScoreMatrix"]]<-CreateAssayObject(mat %>% as.sparse())


DimPlot(t, group.by = "cell_line")

t$cell_line<-factor(t$cell_line, levels = c("hMSC_parent_240",  "hMSC_parent", "hMSC.h7", "RD_parent", "U2OS_parent", "A4573", "A673", "CHLA9", "CHLA10", "PDX305", "RDES", "SKNMC", "TC32", "TC71"))

saveRDS(t, "all_parents_seurat.rds")
```

```{r}
combined_df<-read.csv("/fh/fast/furlan_s/user/owalt/ewings/fusion/pb_fusion_results.csv")
colnames(m1_seu)

str_split(combined_df$cb, "_") %>% sapply("[[", 1) %>% table()

#E1-3 are citeseq samples, EW and EW$ are multiome

combined_df<-combined_df[grep("EW", combined_df$cb),]

ew4<-grepl("EW4", combined_df$cb)
ew4_cbs<-combined_df$cb[ew4]

s1<-ew4_cbs %>% str_split("_") %>% sapply("[[",1)
s2<-ew4_cbs%>% str_split("_") %>% sapply("[[",2)
s3<-ew4_cbs %>% str_split("_") %>% sapply("[[",3)
  # Splitting the string into three parts
combined_df$archr_cb[ew4]<-paste0(s1, "_", s2, "#", s3)


ew1<-!grepl("EW4", combined_df$cb)
ew1_cbs<-combined_df$cb[ew1]

s1<-ew1_cbs %>% str_split("_") %>% sapply("[[",1)
s2<-ew1_cbs%>% str_split("_") %>% sapply("[[",2)
s3<-ew1_cbs %>% str_split("_") %>% sapply("[[",3)
s4<-ew1_cbs %>% str_split("_") %>% sapply("[[",4)
  # Splitting the string into three parts
combined_df$archr_cb[ew1]<-paste0(s1, "_", s2, "_", s3, "#", s4)


archr_cb %>% tail()
table(colnames(m1_seu) %in% combined_df$archr_cb)

fus_df<-combined_df[grepl("EWSR1", combined_df$fusion) & grepl("FLI1", combined_df$fusion),]
mat<-table(colnames(m1_seu) %in% fus_df$archr_cb, m1_seu$cell_line) %>% as.matrix()

meta_fus<-fus_df[!duplicated(fus_df$cb),]

m1_seu$fus<-"NA"
m1_seu$fus[which(colnames(m1_seu) %in% meta_fus$archr_cb)]<-"EWSR1_FLI1"

saveRDS(m1_seu, "all_parents_seurat.rds")
```

